# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_base_joint
      - shoulder_joint
      - bottom_wrist_joint
      - elbow_joint
      - top_wrist_joint
    action_ns: follow_joint_trajectory
    default: true
